language: cpp

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y --force-yes -qq wine
  - git clone https://github.com/CE-Programming/CEmu.git cemu

script:
  - export CEDEV=~/CEdev
  - export PATH=$CEDEV/bin/:$PATH
  - make
  - make install
  - make dist
  - cd $CEDEV/examples
  - make
  - cd cemu/core
  - make
  - cd ../tests/autotester
  - make
  - export PATH=$(pwd):$PATH
  - cd $CEDEV/examples
  - for f in */*.json; do autotester "$f"; done

notifications:
  irc:
    channels:
      - "irc.choopa.net#ez80-dev"
    on_success: change
    on_failure: always
    skip_join: true

